[package]
name = "ripress-wynd"
version = "0.1.0"
edition = "2024"

[dependencies]
ripress = { version = "1.8.6", features = ["with-wynd"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
wynd = { version = "0.4.4", features = ["with-ripress"] }
