[package]
name = "ripress-wynd-minimal-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
ripress = { version = "*", features = ["with-wynd"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wynd = { version = "*", features = ["with-ripress"] }
